# Site specific settings
name: "whitecr0wz.github.io"
keywords: "Key, words, about, this, website"
baseurl: ""
url: "https://whitecr0wz.github.io/"
#description: "Website description"
cover: "/assets/img/cover.svg"
fanpage_id: ""
timezone: America/Argentina/Buenos_Aires
future: true

# Site general settings
lang: "en"
lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: test
twitter: 
facebook: 
github: 
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
